services:
  # Base de datos PostgreSQL
  postgres:
    image: postgres:15
    container_name: auth_postgres
    environment:
      POSTGRES_DB: auth_system
      POSTGRES_USER: auth_user
      POSTGRES_PASSWORD: auth_password_2024
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./backend/init-db.sql:/docker-entrypoint-initdb.d/init-db.sql
    networks:
      - auth_network

  # Backend API
  backend:
    build: ./backend
    container_name: auth_backend
    environment:
      DATABASE_URL: postgresql://auth_user:auth_password_2024@postgres:5432/auth_system
      JWT_SECRET: udistrital_auth_secret_2024_super_secure
      PORT: 3001
    ports:
      - "3001:3001"
    depends_on:
      - postgres
    networks:
      - auth_network
    restart: unless-stopped

  # Frontend
  frontend:
    build: ./frontend
    container_name: auth_frontend
    ports:
      - "8080:80"
    depends_on:
      - backend
    networks:
      - auth_network
    restart: unless-stopped

volumes:
  postgres_data:

networks:
  auth_network:
    driver: bridge