version: '3.8'

services:
  si_ofex:
    build: .
    container_name: si_ofex
    ports:
      - "3000:3000" 
    networks:
      - websiofex
    volumes:
      - ./src:/usr/src/app/src # Sincroniza código local con el contenedor 
    restart: always
    environment:
      - NODE_ENV=development
      - DB_HOST=${DB_HOST} 
      - DB_USER=${DB_USER} # ver .env
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
      - DB_PORT=${DB_PORT}
    depends_on:
      - dbsiofex # Asegura que la DB inicie antes que la app

  # Servicio de la base de datos PostgreSQL
  dbsiofex:
    image: postgres:latest 
    container_name: dbsiofex
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    ports:
      - "5432:5432" 
    networks:
      - websiofex
    volumes:
      - postgres_data:/var/lib/postgresql/data # Persiste
    restart: always

volumes:
  postgres_data: #  persistencia db

networks: # red para el sistema
  websiofex:
    external: true